CREATE TABLE Message (
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255),
    Email VARCHAR(255),
    MessageContent VARCHAR(255),
    MessageDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT MessageId_pk PRIMARY KEY (Id)
)