apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: website
  template:
    metadata:
      labels:
        name: website
    spec:
      containers:
      - name: application
        image: registry.digitalocean.com/website-registry/website:latest
        imagePullPolicy: 'Always'
        ports:
          - containerPort: 80
        env:
          - name: CONN_STRING
            valueFrom:
              secretKeyRef:
                name: website-prod
                key: databaseconnection
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: website-prod
                key: jwtkey
      imagePullSecrets:
        - name: %