apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: website-frontend
  template:
    metadata:
      labels:
        name: website-frontend
    spec:
      containers:
      - name: frontend-server
        image: registry.digitalocean.com/website-registry/website:frontend
        imagePullPolicy: 'Always'
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: registry-website-registry