# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master
      uses: actions/checkout@master

    - name: Inject imagePullSecret into the YAML file
      run: python3 ./kubernetes/insert_imagePullSecrets.py --s ${{ secrets.PRIVATE_REGISTRY_SECRET_NAME }}
    
    - name: Build container image
      run: docker build --tag website:latest -f Frontend.Dockerfile .

    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.0.0
      with:
        # Version of doctl to install
        version: latest
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log into DigitalOcean doctl
      run: doctl registry login
      
    # this was from their docs
    # https://www.digitalocean.com/docs/images/container-registry/quickstart/#push-to-your-registry
    - name: Tag the image in registry
      run: docker tag website:latest registry.digitalocean.com/website-registry/website:latest
      
    - name: Push image to registry
      run: docker push registry.digitalocean.com/website-registry/website:latest
      

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

    - name: Delete current kubernetes deployment
      run: kubectl delete -n default deployment website-app

    - name: Deploy new to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/kubernetes/deployment.yml
